# carplate detector

name: YuCarplateDet
model: 
  activation_type: relu
  backbone:
    type: Yunet
    layers: [[3, 16, 16], [16, 64], [64, 64], [64, 64], [64, 64], [64, 64], [64, 64]]
  head: 
    type: Yuhead
    in_channels: [64, 64, 64, 64]
    num_classes: 2
    num_landmarks: 4
  anchor:
    min_sizes: [[10, 16, 24], [32, 48], [64, 96], [128, 192, 256]]
    steps: [8, 16, 32, 64]
    ratio: [1.2, 2.6]
    clip: True
  loss:
    variance: [0.1, 0.2]
    overlap_thresh: 0.35
    neg_pos: 3
    smooth_point: 0.2
    weight_bbox: 10.
    weight_iouhead: 1.
    weight_lmds: 1.
    weight_cls: 1.

dataset:
  type: DaliLoaderWithLandmarks
  img_root: ./data/CCPD2019/
  annotations_file: ./data/CCPD2019/splits_coco/train.json
  shuffle: True
  shuffle_after_epoch: False
  num_workers: 4
  # multi_scale training
  image_size: [320, 640]

train:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  seed: -1
  batch_size: 32
  start_epoch: 0
  max_epochs: 300
  workspace: ./workspace
  prefix: carplate
  save_interval: 20
  logger: 
    logfile: True
    sysout: True
    tensorboard: True
    log_interval: 50
test:
  multi_scale: False
  confidence_threshold: 0.5
  nms_threshold: 0.3
  keep_top_k: 750
  top_k: 5000  
  ap_threshold: 0.5
  logger:
    logfile: True
    sysout: True
  dataset:
    mode: CCPD
    root: ./data/CCPD2019/
    split: test

