# face detector

name: YuFaceDet
model: 
  activation_type: relu
  backbone:
    type: Yunet
    layers: [[3, 16, 16], [16, 64], [64, 64], [64, 64], [64, 64], [64, 64], [64, 64]]
  head:
    type: Yuhead
    in_channels: [64, 64, 64, 64]
    num_classes: 2
    num_landmarks: 5
  anchor:
    min_sizes: [[10, 16, 24], [32, 48], [64, 96], [128, 192, 256]]
    steps: [8, 16, 32, 64]
    ratio: [1.]
    clip: False
  loss:
    variance: [0.1, 0.2]
    overlap_thresh: 0.35
    neg_pos: 3
    smooth_point: 0.2
    weight_bbox: 10.
    weight_iouhead: 1.
    weight_lmds: 1.
    weight_cls: 1.

dataset:
  type: DaliLoaderWithLandmarks
  img_root: ./data/widerface/WIDER_train/images
  annotations_file: ./data/widerface/trainset.json
  shuffle: True
  shuffle_after_epoch: False
  num_workers: 4
  # multi_scale training
  # image_size: [320, 480]
  image_size: 640

train:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  seed: -1
  batch_size: 16
  start_epoch: 0
  max_epochs: 1000
  workspace: ./workspace
  prefix: face
  save_interval: 50
  logger: 
    logfile: True
    sysout: True
    tensorboard: True
    wandb: False
    log_interval: 20
test:
  multi_scale: False
  confidence_threshold: 0.3
  nms_threshold: 0.3
  keep_top_k: 750
  top_k: 5000  
  ap_threshold: 0.5
  logger:
    logfile: True
    sysout: True
  dataset:
    mode: widerface
    root: ./data/widerface/
    split: val

